### ISSUE TITLE
UTF-8 conversion to latin1 charset may cause issues

### ISSUE THREAD

**Issue by mrivnak** [oatmealandcoffee/al-journey#8]
PyQuery does not decode utf-8 encoded XML if it does not contain a header in the file. To get around this the text from the file must be first encoded to another charset, then decoded with UTF-8. This method may cause crashes if there are characters in the UTF-8 text that are not present in the Latin1 charset. possible solution here is to switch to a different library for parsing the XML data.

**Comment by rboder** [comment]
Read the input file into a string and then pass to PyQuery. String will be stored as Unicode.
